version: "3.9"
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  webapi:
    build:
      context: .
      dockerfile: FDXTestApp.API/Dockerfile
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
    ports:
      - "5000:80"
    depends_on:
      - db
      - rabbitmq

  consumerapp:
    build:
      context: .
      dockerfile: FDXTestApp.Consumer/Dockerfile
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
    depends_on:
      - webapi

  angularapp:
    build:
      context: sms-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - webapi


volumes:
  rabbitmq_data:
